import React from "react";
import Head from "@/components/Head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const TermsAndConditions = () => {
  return (
    <>
      <Head title="Terms and Conditions - ADHYAA PICKLES" />
      <Navbar />
      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>

        <section className="mb-6">
          <p>
            This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name{" "}
            <a href="https://adhyaapickles.in/" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">
              https://adhyaapickles.in/
            </a>{" "}
            ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").
          </p>
          <p>
            The Platform is owned by ADHYAA PICKLES, a company incorporated under applicable laws with its registered office at YENDAPALLI, KRUTHIVENNU MANDAL, KRISHNA DISTRICT, 521324 (hereinafter referred to as “Platform Owner”, "we", "us", "our").
          </p>
          <p>
            Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
          </p>
          <p>
            These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, "Services"). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
          <p>
            For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="font-semibold uppercase">
            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Use of Platform and Services</h2>
          <p>
            You agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
          </p>
          <p>
            Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
          </p>
          <p>
            Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.
          </p>
          <p>
            The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.
          </p>
          <p>
            You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
          </p>
          <p>
            You agree to pay us the charges associated with availing the Services.
          </p>
          <p>
            You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
          </p>
          <p>
            The website and Services may contain links to third party websites. Accessing these links will subject you to their terms and privacy policies. These are provided for convenience only.
          </p>
          <p>
            You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner.
          </p>
          <p>
            You shall indemnify and hold harmless Platform Owner, its affiliates, group companies, and their respective officers, directors, agents, and employees from any claims or demands arising from your breach of these Terms or violation of any law or third-party rights.
          </p>
          <p>
            Platform Owner shall not be liable for any failure to perform an obligation under these Terms if such performance is prevented or delayed by a force majeure event.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Governing Law and Jurisdiction</h2>
          <p>
            These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Machilipatnam,Andhra Pradesh
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Contact Information</h2>
          <p>
            All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default TermsAndConditions;
