// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwewngssolzrlwgvqknv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZXduZ3Nzb2x6cmx3Z3Zxa252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjkyMTUsImV4cCI6MjA1NTU0NTIxNX0.N64Mx0AtkhlFXOx9wWPNTQs-JiCAAxo4SWvSNgEDlhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);